### ISSUE TITLE
When I tried to use the 2018 Finn, my CCTM script showed an error

### ISSUE THREAD

**Issue by bandaoshutiao** [barronh/finn2cmaq#2]
```
     Error opening file at path-name:
     netCDF error number  -51  processing file "GR_EMIS_001"
     NetCDF: Unknown file format
     NetCDF: Unknown file format
     /data4/sunzhixu/outdata/emis/finn/FINNv1.5_2018-06-26.GEOSCHEM.nc
```
I can open these files with the ncdump command.
In fact, at first, my ncdump couldn't open this file until I changed the original NetCDF path in bashrc to another friend's NetCDF in the server.However, after I modified the NetCDF path in CMAQ config and recompiled it, the CCTM script still reported this error.

I am a beginner，I'm sorry to take up your personal time.

But I really don't know how to solve it，I've been trying to solve it for days.

**Comment by barronh** [comment]
If I understand you correctly, you've made the emission file and you're trying to use it when you get this error. I suspect I know what the issue is.

By default, the scripts save the files in "NetCDF-4 classic model." You'll see this in the scripts as format="NETCDF4_CLASSIC". A netcdf library compiled without netcdf4 support will not be able to open it. CMAQ uses IOAPI as an interface to the netcdf library. So, CMAQ can only read a NETCDF4_CLASSIC file if IOAPI was complied using an IOAPI library that was compiled against a netcdf library with NetCDF-4 support.

The easiest way to test this theory is convert the file to NetCDF3. See if you (or your friend) has `nccopy`.[1] If so, you can copy one of these files to NetCDF-3 and see if the new file can be read then. That requires two steps.

Step 1: translate the file. See command below.
```
nccopy -3 /data4/sunzhixu/outdata/emis/finn/FINNv1.5_2018-06-26.GEOSCHEM.nc /data4/sunzhixu/outdata/emis/finn/FINNv1.5_2018-06-26.GEOSCHEM.nc3
```

Step 2: Edit your CMAQ run script to change `GR_EMIS_001` to point to the new (.nc3) version of the file.

The benefit of NetCDF-4 classic model is that it uses compression to make the files smaller. In NetCDF3, they will be much bigger. One option is to use nccopy in your CMAQ script. Basically, make a NetCDF3 copy for the day, process the day, then get rid of the NetCDF3 file to save space.

Does that work?

[1] https://www.unidata.ucar.edu/software/netcdf/workshops/2011/utilities/Nccopy.html

**Comment by barronh** [comment]
p.s., Sorry it took so long to respond. I was on vacation.

**Comment by bandaoshutiao** [comment]
[CTM_LOG_000.cb6r3_ae7_aq_intel_cn36_2018_20180626.txt](https://github.com/barronh/finn2cmaq/files/8480396/CTM_LOG_000.cb6r3_ae7_aq_intel_cn36_2018_20180626.txt)

hi
It doesn't matter, you are willing to help me, I am already very grateful.
When I modified it according to the method you said, my CMAQ run script generated a log with a lot of content. I couldn't understand what the error was. Is it because of the species?

**Comment by bandaoshutiao** [comment]
I found an interesting thing when I used the method you taught me.
When I use the emissions inventory produced by the 2018 FINN compressed package on the official website, the script will report this error, but when I use the emissions inventory produced by the daily compressed package starting with GLOB in 2020, it can be run.

**Comment by barronh** [comment]
The log that you sent is for processor 0 (the first). It ends without an error. If you are running with multiple processors, then there will be multiple logs (CTM_LOG_000 ... CTM_LOG_???). At the bottom of one of them, you'll see an error.

Basically, you need to review the end of each log looking for something that went wrong. The command below will help.

```
tail CTM_LOG_???.*
```

**Comment by bandaoshutiao** [comment]
[CTM_LOG_001.cb6r3_ae7_aq_intel_cn36_2018_20180626.txt](https://github.com/barronh/finn2cmaq/files/8499497/CTM_LOG_001.cb6r3_ae7_aq_intel_cn36_2018_20180626.txt)
Every log file is the same and doesn't seem to directly explain the reason for the error.

**Comment by barronh** [comment]
Are there files named core.????? In the scripts folder?

**Comment by bandaoshutiao** [comment]
There really is no such file, and I don't know why       :(

But after using the method you said I was able to use this file, thank you~~ you are such a gentleman~~

**Comment by bandaoshutiao** [comment]
I haven't checked my github recently because of some things, sorry for the late reply. I will find out the reason for the previous file error in the near future~~
